const SUPABASE_URL="https://qqwifsgnzweslkcyuqmg.supabase.co";
const SUPABASE_KEY="sb_publishable_AI6rSMSOAag61TCJzapLbg_frex6ks9";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const CRED={user:"irancraft"};const $=id=>document.getElementById(id);
const statusNames={pending:"در انتظار بررسی",approved:"تأیید شد",in_progress:"در حال انجام",ready:"آماده تحویل",rejected:"رد شد"};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function auth(){if(document.body.dataset.page!=="admin"){$("site")?.classList.remove("hidden");return}if(sessionStorage.getItem("irancraft_login")==="1"){$("loginGate")?.classList.add("hidden");$("adminSite")?.classList.remove("hidden");loadAdmin();return}$("loginForm")?.addEventListener("submit",e=>{e.preventDefault();if($("loginUser").value.trim()===CRED.user){sessionStorage.setItem("irancraft_login","1");location.reload()}else $("loginError").textContent="نام کاربری اشتباه است."})}
$("logoutBtn")?.addEventListener("click",()=>{if(document.body.dataset.page==="admin"){sessionStorage.removeItem("irancraft_login");location.reload()}});
function openOrder(type){$("orderSection").classList.remove("hidden");$("orderType").value=type;const h=type==="herobrine";$("formTitle").textContent=h?"سفارش اضافه کردن هیروبراین":"سفارش ساخت ماد برای سرور";$("serverFields").style.display=h?"grid":"none";$("serverName").required=h;$("serverAddress").required=h;$("orderSection").scrollIntoView({behavior:"smooth"})}
document.querySelectorAll(".service-open").forEach(b=>b.onclick=()=>openOrder(b.dataset.service));$("closeForm")?.addEventListener("click",()=>$("orderSection").classList.add("hidden"));
const savedProfile=JSON.parse(localStorage.getItem("irancraft_profile")||"{}");if($("customerName")&&savedProfile.name)$("customerName").value=savedProfile.name;if($("customerPhone")&&savedProfile.phone)$("customerPhone").value=savedProfile.phone;$("orderForm")?.addEventListener("submit",async e=>{e.preventDefault();const type=$("orderType").value;const name=$("customerName").value.trim(),phone=$("customerPhone").value.trim();localStorage.setItem("irancraft_profile",JSON.stringify({name,phone}));const {data,error}=await db.from("irancraft_orders").insert({order_type:type,customer_name:name,customer_phone:phone,username:$("orderUsername").value.trim(),server_name:$("serverName").value.trim()||null,server_address:$("serverAddress").value.trim()||null,description:$("description").value.trim()}).select().single();const r=$("orderResult");r.classList.remove("hidden");if(error){r.textContent="خطا در ثبت سفارش: "+error.message;return}r.innerHTML="✅ سفارش ثبت شد.<br>کد تیکت: <b>"+data.ticket_code+"</b><br><small>کد را نگه دار و از بخش پیگیری استفاده کن.</small>";e.target.reset()});
$("ticketForm")?.addEventListener("submit",async e=>{e.preventDefault();const code=$("ticketCode").value.trim().toUpperCase(),r=$("ticketResult");r.classList.remove("hidden");const {data,error}=await db.from("irancraft_orders").select("*").eq("ticket_code",code).maybeSingle();if(error||!data){r.textContent="تیکتی با این کد پیدا نشد.";return}r.innerHTML="<b>"+(data.order_type==="herobrine"?"👁️ سفارش هیروبراین":"🧩 سفارش ساخت ماد")+"</b><br>وضعیت: <strong class='status "+data.status+"'>"+(statusNames[data.status]||data.status)+"</strong><br><small>"+esc(data.admin_note||"هنوز توضیحی ثبت نشده است.")+"</small>"+(data.file_url?"<br><a class='btn primary' target='_blank' href='"+data.file_url+"'>⬇️ دریافت فایل ماد</a>":"")});
let adminType="herobrine",orders=[];
async function loadAdmin(){const {data,error}=await db.from("irancraft_orders").select("*").order("created_at",{ascending:false});if(error){$("orders").innerHTML="<div class='empty'>خطا در دریافت سفارش‌ها.</div>";return}orders=data||[];$("countHero").textContent=orders.filter(x=>x.order_type==="herobrine").length;$("countMod").textContent=orders.filter(x=>x.order_type==="mod").length;renderOrders()}
function renderOrders(){ $("adminTitle").textContent=adminType==="herobrine"?"سفارش‌های هیروبراین":"سفارش‌های ساخت ماد";const list=orders.filter(x=>x.order_type===adminType);if(!list.length){$("orders").innerHTML="<div class='empty'>هنوز سفارشی در این بخش نیست.</div>";return} $("orders").innerHTML=list.map(o=>"<article class='order-card'><div class='order-top'><div><span class='order-code'>"+o.ticket_code+"</span><h3>"+esc(o.customer_name)+" — "+esc(o.username)+"</h3></div><span class='status "+o.status+"'>"+(statusNames[o.status]||o.status)+"</span></div><div class='order-meta'>"+(o.server_name?"🧱 "+esc(o.server_name):"")+(o.server_address?"　🌐 "+esc(o.server_address):"")+"　🕒 "+new Date(o.created_at).toLocaleString("fa-IR")+"</div><div class='order-description'><b>توضیحات مشتری:</b><p>"+esc(o.description)+"</p></div><div class='admin-edit'><label>وضعیت<select data-status='"+o.id+"'>"+Object.entries(statusNames).map(([k,v])=>"<option value='"+k+"' "+(o.status===k?"selected":"")+">"+v+"</option>").join("")+"</select></label><label>توضیحات ادمین<textarea data-note='"+o.id+"' rows='3'>"+esc(o.admin_note||"")+"</textarea></label>"+(o.order_type==="mod"?"<label>فایل ماد<input type='file' data-file='"+o.id+"' accept='.jar,.zip,.mcpack,.mcaddon,.rar'></label>":"")+"<div class='edit-actions'><button class='btn primary save-order' data-id='"+o.id+"'>تأیید و ذخیره</button>"+(o.file_url?"<a class='btn ghost' target='_blank' href='"+o.file_url+"'>فایل فعلی</a>":"")+"</div></div></article>").join("");document.querySelectorAll(".save-order").forEach(b=>b.onclick=()=>saveOrder(b.dataset.id))}
async function saveOrder(id){const o=orders.find(x=>x.id===id);if(!o)return;let file_url=o.file_url,file_name=o.file_name;const input=document.querySelector("[data-file='"+id+"']");if(input?.files?.[0]){const f=input.files[0],path=id+"/"+Date.now()+"_"+f.name.replace(/[^\w.\-\u0600-\u06ff]/g,"_");const up=await db.storage.from("irancraft-mods").upload(path,f,{upsert:true});if(up.error){alert("آپلود ناموفق: "+up.error.message);return}file_url=db.storage.from("irancraft-mods").getPublicUrl(path).data.publicUrl;file_name=f.name}const {error}=await db.from("irancraft_orders").update({status:document.querySelector("[data-status='"+id+"']").value,admin_note:document.querySelector("[data-note='"+id+"']").value,file_url,file_name,updated_at:new Date().toISOString()}).eq("id",id);if(error){alert("ذخیره نشد: "+error.message);return}await loadAdmin();alert("سفارش ذخیره شد.")}
document.querySelectorAll(".admin-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");adminType=b.dataset.tab;renderOrders()});$("refreshOrders")?.addEventListener("click",loadAdmin);auth();